### ISSUE TITLE
Gestión de clientes

### ISSUE THREAD

**Issue by gmllasacas** [gmllasacas/gym#6]
Campos al momento del registro:
- Nombres
- Apellidos
- DNI
- Correo
- Telefono
- Fecha Nacimiento
- Nota, ej: Algun tipo de enfermedad
- Nombre Contacto de Emergencia
- Teléfono Contacto de Emergencia
- Código de cliente: Incremental y no editable
- Departamento (oculto, definido en Ancash)
- Provincia
- Distrito
- Dirección

Agregar el filtro por campo, adicionar una lista desplegable con el valor de cada campo al costado del campo de texto
Filtro de clientes con membresía por vencer ( Menor igual a 7 dias)

Columnas a mostrar:
- CODIGO
- NOMBRE
- APELLIDO
- TIPO DE MEMBRESIA
- ESTADO
- DIAS POR VENCER MEMBRESIA

Al exportar se debe de obtener:
- CODIGO
- DNI
- NOMBRE APELLIDO
- TIPO DE MEMBRESIA
- ESTADO
- DIAS POR VENCER MEMBRESIA
- TELEFONO
- CORREO
- PROVINCIA
- DISTRITO

**Comment by SomBody** [comment]
Al momento de la transacción se debe de llenar:
Tipo de Membresia
Fecha Inicio:
Fecha Fin
Dias Plan:

**Comment by SomBody** [comment]
Agregar el filtro por campo, adicionar una lista desplegable con el valor de cada campo al costado del campo de texto

**Comment by SomBody** [comment]
Al exportar se debe de obtener:
CODIGO
DNI
NOMBRE APELLIDO
TIPO DE MEMBRESIA
ESTADO
DIAS POR VENCER MEMBRESIA
TELEFONO
CORREO

**Comment by SomBody** [comment]
Manejar el nombre y apellido en un solo campo ** Queda como pendiente si se mejora o no

**Comment by gmllasacas** [comment]
@SomBody algo que me di cuenta, es que al mencionar que se requiere que la columna de membresía y días existan, quiere decir que el cliente solo puede tener una membresía activa a la vez?
Podrías revisar tus apuntes para validar esto?
